### ISSUE TITLE
帮助 Rikka 完成关于通知可以具体进入对应聊天

### ISSUE THREAD

**Issue by RikkaW** [RikkaW/FCM-for-Mojo#14]
简单的说目标就是获得正常 QQ 发送的通知的 `contentIntent` 对应的 `Intent`，然后看看他的 extra 呀什么的是什么。

#### 7.0 以下
开一个 ```NotificationListenerService```，并反射使用 ```sbn.getNotification().contentIntent.getIntent()``` 就可以。

#### 7.0 以上
``` pendingIntent.getIntent();``` 实际执行的是 
 ```ActivityManagerNative.getDefault() .getIntentForIntentSender(pendingIntent.mTarget);```（7.0 开始需要一个系统签名保护的权限）

那就可以用一个绕一下的办法，root 使用 app_process 在启动的进程中使用 ```ServiceManager.addService``` 添加一个系统服务，并在其中提供 ```getIntentForIntentSender```，其他应用就可以使用该服务来调用本来无权调用的 API。

已经用这样的方法完成的
- [x] 普通的 QQ 系列
- [x] TIM （应该和普通的一样）
- [ ] 国际版系列

**Comment by haruue** [comment]
#32
