### ISSUE TITLE
无法回复，显示“Failed to connect to /0.0.0.0:5000”

### ISSUE THREAD

**Issue by ShadowLyin** [RikkaW/FCM-for-Mojo#15]
Android 版本：7.1.2 ，LineageOS 14.1
手机型号：MI 5s Plus
app 版本：v0.3.0-alpha2，v0.2.1
Linux 系统：Centos 6.9 64bit
GCM.pl 内容如下：
use Mojo::Webqq;
my $client = Mojo::Webqq->new(log_encoding=>"utf-8");
$client->load("ShowMsg");
$client->load(
'RikkaGCM',
   data => {
        api_url => 'https://fcm.googleapis.com/fcm/send',
        api_key => 'AAAABvjXwsM:APA91bF0X8YKcyTJcUdTLB1lc6Xb-03eIHCLy7PKHCwVYCL6XqEB7eS8o3i0amPOPi-R4i_ldlVtnPcYLtf4DwS4qgTi5Ra8Uyl9pGT02iJDE9Ovc-5dUoNSpgWUUZPn0KN2gJjeYLhO',
        registration_ids => ['d_3vbCcV8HI:APA91bHHe7peuFNUuEGkmsxCWYD7U3chE0tVLYFaucSVLHE5nHjC74DD_zzLkIfWDKGOj0g2ko22wxrzT-0y3d7P-E46LT7ioRpfIryv7L4y4m79gnbpoWzUZNvy3iRhLFKyrQ5p3GRt']
        # ... #
    }
);
$client->load("Openqq",data=>{
    listen => [{host=>"0.0.0.0",port=>5000}, ] ,
});
$client->run();

**Comment by RikkaW** [comment]
等一下.. 看起来你是没在 app 里设置服务器地址 吧..（

**Comment by ShadowLyin** [comment]
app里面不是默认0.0.0.0/5000吗？

**Comment by RikkaW** [comment]
这个要改成自己的呀..
