### ISSUE TITLE
ffm客户端bug

### ISSUE THREAD

**Issue by manyang901** [RikkaW/FCM-for-Mojo#19]
无论是否配置okhttp验证，ffm客户端都会将请求发到
serv…ip/127.0.0.1:端口号
当然failed to connect to ...了啊
推送可以使用，但无弹窗
回复功能因上述bug无法使用
ffm客户端版本最新alpha2

**Comment by manyang901** [comment]
0.1.2版本可以正常回复

**Comment by manyang901** [comment]
无弹窗发现为系统通知权限问题，并非bug

**Comment by manyang901** [comment]
加入nginx反代身份验证后请求的url错误
为bug

**Comment by WordlessEcho** [comment]
没法听懂你的描述
