### ISSUE TITLE
需要重写教程

### ISSUE THREAD

**Issue by RikkaW** [RikkaW/FCM-for-Mojo#22]

**Comment by WordlessEcho** [comment]
等 Rikka 的稳定版发布并且向上游项目 push 文件后，我会重写教程

**Comment by WordlessEcho** [comment]
TODO:
- [ ] Greenhorn friendly. (More clear)
- [ ] Import English version.
- [ ] Use ```nano``` instead of ```vim```?
- [ ] Add download to releases and warning for pre-releases.
- [ ] Import example.

**Comment by WordlessEcho** [comment]
I am working about that in my [fork](https://github.com/WordlessEcho/FCM-for-Mojo).
BTW: I think FFM client should have a guide for new users.
