### ISSUE TITLE
请问如何设置https

### ISSUE THREAD

**Issue by ZenusShadow** [RikkaW/FCM-for-Mojo#26]
RT，当前最新版的FFM和那个index.js默认是http连接，我想使用https连接，请问应该如何修改index.js

**Comment by WordlessEcho** [comment]
Rikka will release a new version to do it. If you couldn't wait for trying, see here: [Use HTTPS instead of HTTP](https://github.com/RikkaW/FCM-for-Mojo/pull/25/files).
Also, you can use Nginx to proxy Node.js.

BTW, next version will have a big changes. This way **only for test**.

**Comment by WordlessEcho** [comment]
Update: already released.
