### ISSUE TITLE
第一次使用时需要手动扫码

### ISSUE THREAD

**Issue by simonsmh** [RikkaW/FCM-for-Mojo#27]
GOT 502 when "GET /ffm/registration_ids" but no ids in config. It's possibly a logical error.
Open app and setting -> 
GET & Receive 502 (nodejs) or timeout (nginx) -> 
"Update registration id" Button not showing up -> 
Never POST /ffm/update_registration_ids ->
GET & Receive 502 (nodejs) or timeout (nginx) AGAIN

**Comment by simonsmh** [comment]
Well, should there have a fix in FFM perl module or just give another try in the Android client?

**Comment by WordlessEcho** [comment]
The right request is ```/ffm/get_registration_ids``` and ```/ffm/update_registration_ids```.
But it should return 404.

**Comment by WordlessEcho** [comment]
I met your problem before. Because I input HTTPS at server address, but it should be HTTP. XP
So I guess it's a problem of configurations, maybe you should post it here.

**Comment by simonsmh** [comment]
> no ids in config
The configuration on start is `{}`
On client, Both http/https concerning problem has been tested, including CDN or none CDN, domain with or without hsts under http or https, and IP. And server just return nothing.
