### ISSUE TITLE
需要把推送移到 node

### ISSUE THREAD

**Issue by RikkaW** [RikkaW/FCM-for-Mojo#30]
node 退出时需要推送一个服务端完全退出的消息，如果 node 和 perl 都写就会怪怪的..

**Comment by WordlessEcho** [comment]
我的想法是，使两者都可以后台运行，然后写一个 ```stop.sh``` 专门做这样的事

**Comment by haruue** [comment]
不用吧。。node 服务端连接不上的时候就说明服务端已经完全退出了，弹一条通知就可以啦～
