### ISSUE TITLE
Failed to execute node node/index.js with the latest release(v0.3.4-1)

### ISSUE THREAD

**Issue by SingSky** [RikkaW/FCM-for-Mojo#44]
### The Error messages are as following:
[root@pixel node]# node index.js 
[FFM] client config file: client.json
[FFM] starting Mojo-Webqq...
[]
[FFM] no https configuration found
[FFM] no basic auth configuration found
[FFM] listening 5005
Can't open perl script "perl/start.pl": No such file or directory

**Comment by haruue** [comment]
You should get latest [server.zip](https://github.com/RikkaW/FCM-for-Mojo/releases/latest), unzip it and start server by `node node/index.js`. 

Server configuration method has modify and old method won't work properly after [v0.3.0-alpha3](https://github.com/RikkaW/FCM-for-Mojo/releases/tag/v0.3.0-alpha3). If you don't want to update your server, you can use [v0.3.0-alpha2](https://github.com/RikkaW/FCM-for-Mojo/releases/tag/v0.3.0-alpha2)

If you can't understand Chinese, please refer to [this guide](https://github.com/WordlessEcho/FCM-for-Mojo/blob/3fb0fe09f0e197ce3a0ede58a90d4344407e5e9a/README.md#get-server) for starting a server of recent release. 
如果你懂中文，请直接看 [这个](https://github.com/RikkaW/FCM-for-Mojo/blob/master/server/README.md)

**Comment by SingSky** [comment]
Thanks and sorry for my carelessness...

**Comment by WordlessEcho** [comment]
Don't ```cd``` to node to running this command.
