### ISSUE TITLE
「特权接口服务」并不请求 root 权限

### ISSUE THREAD

**Issue by WordlessEcho** [RikkaW/FCM-for-Mojo#5]
目前使用的是 Magisk Su

**Comment by RikkaW** [comment]
坏耶 等新的

**Comment by WordlessEcho** [comment]
![screenshot_20170523-181049](https://cloud.githubusercontent.com/assets/12007025/26349780/8fac8efa-3f76-11e7-82a9-6db7ce914fef.png)
我发现了一个问题，Magisk 似乎将特权 API 服务和酷安混在了一起，酷安已经被我卸载了
所以说这个是 Magisk 的问题吗

**Comment by RikkaW** [comment]
不知道啦（

**Comment by WordlessEcho** [comment]
好不负责的回答（
坏耶

**Comment by aviraxp** [comment]
是 magisk 的问题。我已经报了，下次更新修复

**Comment by WordlessEcho** [comment]
@aviraxp 麻烦 refer 一下，感谢
