### ISSUE TITLE
在Android 8.0下无法收到二维码通知

### ISSUE THREAD

**Issue by Mr-Bubble** [RikkaW/FCM-for-Mojo#53]
机型：Bacon
系统：aosp-8.0.0
无法收到二维码通知{GCM推送正常,下面有截图},也就无法点击跳转到tim来扫码,只能手动打开 从Download/FFM/下手动扫码.{手动扫码后消息推送正常通知正常}

![screenshot_20170910-182347](https://user-images.githubusercontent.com/15337062/30248235-60e485a0-9656-11e7-9469-7b80e9ceac66.png)

log:
--------- beginning of system
09-10 18:14:33.656  1502  2444 D ConnectivityService: reportNetworkConnectivity(100, true) by 10027
09-10 18:14:33.673 19305 19352 D MessagingService: {"type":"3","message":{"sender":"input_qrcode","content":"https:\/\/i.loli.net\/2017\/09\/10\/59b51089d4358.png","timestamp":1505038465}}
09-10 18:14:33.695  1502  2402 D PackageManager: [707f3408-11ce-431e-94c5-36302472077c] Phase1; resolving
09-10 18:14:33.696  2257  2717 V PackageManager: [707f3408-11ce-431e-94c5-36302472077c] Phase1 called; posting
09-10 18:14:33.696  2257  2257 D PackageManager: [707f3408-11ce-431e-94c5-36302472077c] Phase1 request; prefix: [-1554595840, 285712384]
09-10 18:14:33.697  1502  2402 D PackageManager: [707f3408-11ce-431e-94c5-36302472077c] Phase1; No results matched
09-10 18:14:33.920  2932  2932 W Notification: Use of stream types is deprecated for operations other than volume control
09-10 18:14:33.920  2932  2932 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
09-10 18:14:34.005  2295  2307 D MediaProvider: object removed 37857
09-10 18:14:34.097  2295  2295 D MediaScannerReceiver: action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Download/FFM/webqq-qrcode.png
09-10 18:14:34.109  2295  2166 D skia    : --- SkAndroidCodec::NewFromStream returned null
09-10 18:14:34.243 19305  2152 W Notification: Use of stream types is deprecated for operations other than volume control
09-10 18:14:34.243 19305  2152 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
09-10 18:14:34.246  2295  2295 D MediaScannerReceiver: action: android.intent.action.MEDIA_SCANNER_SCAN_FILE path: /storage/emulated/0/Download/FFM/webqq-qrcode.png
09-10 18:14:34.247  1502  2410 E NotificationService: No Channel found for pkg=moe.shizuku.fcmformojo, channelId=server_channel, id=-10001, tag=null, opPkg=moe.shizuku.fcmformojo, callingUid=10070, userId=0, incomingUserId=0, notificationUid=10070, notification=Notification(channel=server_channel pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x10 color=0xff3f51b5 vis=PRIVATE)
09-10 18:14:34.276  3892  3892 I RenderThread: type=1400 audit(0.0:2811): avc: denied { ioctl } for path="/dev/kgsl-3d0" dev="tmpfs" ino=8279 ioctlcmd=913 scontext=u:r:system_server:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
09-10 18:14:34.276  3892  3892 I RenderThread: type=1400 audit(0.0:2812): avc: denied { read write } for path="/dev/kgsl-3d0" dev="tmpfs" ino=8279 scontext=u:r:system_server:s0 tcontext=u:object_r:device:s0 tclass=chr_file permissive=1
09-10 18:14:34.279  1502  3892 I OpenGLRenderer: Initialized EGL, version 1.4
09-10 18:14:34.279  1502  3892 D OpenGLRenderer: Swap behavior 1
09-10 18:14:34.284  1502  3892 W Adreno-EGL: <qeglDrvAPI_eglGetConfigAttrib:607>: EGL_BAD_ATTRIBUTE
09-10 18:14:34.284  1502  3892 I vndksupport: sphal namespace is not configured for this process. Loading /vendor/lib/hw/gralloc.msm8974.so from the current namespace instead.
09-10 18:14:34.932  2932  2932 W Notification: Use of stream types is deprecated for operations other than volume control
09-10 18:14:34.932  2932  2932 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
09-10 18:14:35.944  2932  2932 W Notification: Use of stream types is deprecated for operations other than volume control
09-10 18:14:35.944  2932  2932 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
09-10 18:14:36.295  1502  1502 W WindowManager: removeWindowToken: Attempted to remove non-existing token: android.os.Binder@968ae6e
09-10 18:14:36.339  1502  2175 V rsC++   : RS Message thread exiting.
09-10 18:14:36.993  2932  2932 W Notification: Use of stream types is deprecated for operations other than volume control
09-10 18:14:36.993  2932  2932 W Notification: See the documentation of setSound() for what to use instead with android.media.AudioAttributes to qualify your playback use case
09-10 18:14:37.027 16070 16125 I CastDatabase: Saving the database
09-10 18:14:37.028 16070 16125 I SQLiteCastStore: Saving 0 CastNetworkInfo instances, 0 CastDeviceInfo instances, 0 paired guest mode devices.
09-10 18:14:37.104 16070 16125 E SQLiteCastStore: End saving paired guest mode devices

**Comment by RikkaW** [comment]
等下一个 release 吧..

**Comment by Mr-Bubble** [comment]
ok
