### ISSUE TITLE
向「服务器 URL」中加入奇怪的东西会导致应用崩溃

### ISSUE THREAD

**Issue by WordlessEcho** [RikkaW/FCM-for-Mojo#7]
举例：```https://gongjianwei/apis```，应用随后就会崩溃而无法打开
错误日志：
```
05-25 13:22:26.260 E/ActivityManager(3823): Sending non-protected broadcast moe.shizuku.privileged.api.intent.action.TASK_STACK_CHANGED from system uid 0 pkg null
```

**Comment by RikkaW** [comment]
好麻烦

**Comment by haruue** [comment]
感觉只要 malformed 了就会崩溃，Rikka 能不能 handle 一下这个呢？
可能有帮助的方法
https://developer.android.com/reference/android/webkit/URLUtil.html#isHttpUrl(java.lang.String)
https://developer.android.com/reference/android/webkit/URLUtil.html#isHttpsUrl(java.lang.String)
